# === STARSHIP CONFIG === #

format = """
[  ](bg:color_bg1)\
$os\
$username\
[](fg:color_bg1 bg:color_aqua)\
$directory\
[](fg:color_aqua bg:color_blue)\
[](fg:color_blue bg:color_bg3)\
[](fg:color_bg3 bg:color_bg1)\
[](fg:color_bg1 )\
$line_break\
[  󱞪 ](fg:color_aqua)
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#a6e3a1'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_green2 = '#e3f1ce'

[os]
disabled = false
style = "bg:color_bg1 fg:color_green2"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Arch = "󰣇"

[username]
show_always = true
style_user = "fg:color_green2 bg:color_bg1"
style_root = "fg:color_green2 bg:color_bg1"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg1 bg:color_aqua"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[line_break]
disabled = false
