#! /bin/sh

# Monitor layout
xrandr --output HDMI-1 --primary --auto --output eDP-1 --auto --below HDMI-1

# Workspaces
bspc monitor HDMI-1 -d 1 2 3 4 5 6
bspc monitor eDP-1 -d 1 2 3 4 5 6

# Configs
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# Colors
bspc config normal_border_color "#444444"
bspc config focused_border_color "#88c0d0"

# Inicializar

# Lanzar Polybar por monitor
killall -q polybar
sleep 1
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  MONITOR=$m ~/.config/polybar/launch.sh &
done

sxhkd -c ~/.config/sxhkd/sxhkdrc &
