#! /bin/sh

# Monitor layout
xrandr --output HDMI-1 --primary --auto --output eDP-1 --auto --below HDMI-1

# Workspaces
bspc monitor HDMI-1 -d 1 2 3 4 5 6

# Configs
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

# Colors
bspc config normal_border_color "#444444"
bspc config focused_border_color "#88c0d0"

# Inicializar
polybar main &
sxhkd -c ~/.config/sxhdk/sxhkdrc &
